run:
  timeout: 10m
  skip-dirs:
    - gen
    - vendor

linters:
  disable-all: true
  enable:
    - dupl
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - unused
    - staticcheck
    - godot

linters-settings:
  gofmt:
    simplify: true
  dupl:
    threshold: 400