package config

const (
	BeginString              string = "BeginString"
	SenderCompID             string = "SenderCompID"
	TargetCompID             string = "TargetCompID"
	SessionQualifier         string = "SessionQualifier"
	SocketAcceptPort         string = "SocketAcceptPort"
	SocketConnectHost        string = "SocketConnectHost"
	SocketConnectPort        string = "SocketConnectPort"
	SocketPrivateKeyFile     string = "SocketPrivateKeyFile"
	SocketCertificateFile    string = "SocketCertificateFile"
	SocketCAFile             string = "SocketCAFile"
	DefaultApplVerID         string = "DefaultApplVerID"
	DataDictionary           string = "DataDictionary"
	TransportDataDictionary  string = "TransportDataDictionary"
	AppDataDictionary        string = "AppDataDictionary"
	ResetOnLogon             string = "ResetOnLogon"
	ResetOnLogout            string = "ResetOnLogout"
	ReconnectInterval        string = "ReconnectInterval"
	HeartBtInt               string = "HeartBtInt"
	FileLogPath              string = "FileLogPath"
	FileStorePath            string = "FileStorePath"
	SQLDriver                string = "SQLDriver"
	SQLDataSourceName        string = "SQLDataSourceName"
	SQLConnMaxLifetime       string = "SQLConnMaxLifetime"
	ValidateFieldsOutOfOrder string = "ValidateFieldsOutOfOrder"
)
